theme: jekyll-theme-slate
url: "https://AeroOwl.github.io"
baseurl: ""
paginate:            1

# Permalinks
permalink:           pretty

author:
  name:              ayC

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  
default:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
