theme: jekyll-theme-slate
url: "https://AeroOwl.github.io"
baseurl: ""
paginate:            1

# Permalinks
permalink:           pretty

author:
  name:              ayC

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
