theme: jekyll-theme-slate
url: "https://AeroOwl.github.io"
baseurl: ""

defaults:
    scope:
      path: ''
      type: 'posts'
    value:
      layout: ''
      author: 'ayc'
      comments: false
      share: false
